// Generated by scripts/generate_siddur_static_navigation.py. Do not edit.
#pragma once

namespace Data {

inline constexpr std::array<MenuEntry, 2> CATEGORY_0_ITEMS{{
    {"calendar_menu", "Calendar and Zmanim", "לוח שנה וזמנים"},
    {"reminders", "Reminders", "תזכורות"},
}};

inline constexpr std::array<MenuEntry, 10> CATEGORY_1_ITEMS{{
    {"omer_menu", "The Counting of the Omer", "ספירת העומר"},
    {"ushpizin_menu", "Ulu Ushpizin", "עולו אושפיזין"},
    {"lag_omer_menu", "Lag BaOmer", "לג בעומר"},
    {"levana_menu", "Birkat HaLevana", "ברכת הלבנה"},
    {"havdala_menu", "Havdala", "הבדלה"},
    {"hanuka_menu", "Hanuka Lighting", "הדלקת נר חנוכה"},
    {"ilanot_menu", "Birkat HaIlanot", "ברכת האילנות"},
    {"kinot_menu", "Kinnot", "קינות"},
    {"slichotMenu", "Slichot", "סליחות"},
    {"nedarimMenu", "Annullment of Vows", "התרת נדרים"},
}};

inline constexpr std::array<MenuEntry, 6> CATEGORY_2_ITEMS{{
    {"shacharit_menu", "Shacharit", "שחרית"},
    {"mincha_menu", "Mincha", "מנחה"},
    {"arvit_menu", "Arvit", "ערבית"},
    {"asher_yatzar_menu", "Asher Yatzar", "אשר יצר"},
    {"bedtime_shma_menu", "Bedtime Shma", "קריאת שמע שעל המיטה"},
    {"chatzot_menu", "Tikun Chatzot", "תיקון חצות"},
}};

inline constexpr std::array<MenuEntry, 8> CATEGORY_3_ITEMS{{
    {"mazon_menu", "Birkat HaMazon", "ברכת המזון"},
    {"threefold_menu", "The Threefold Blessing", "מעין שלוש"},
    {"hala_menu", "Dough offering", "הפרשת חלה"},
    {"other_blessings_menu", "Other Blessings", "ברכות נוספות"},
    {"maaser_menu", "Tithes", "הפרשת תרומות ומעשרות"},
    {"haderech_menu", "The Traveler's Prayer", "תפילת הדרך"},
    {"mila_menu", "Brit Mila", "ברית מילה"},
    {"sheva_brachot_menu", "Sheva Berachot", "שבע ברכות"},
}};

inline constexpr std::array<Category, 4> CATEGORIES{{
    {{"calendar_menu_group", "Calendar and Zmanim", "לוח שנה וזמנים"},
     CATEGORY_0_ITEMS.data(),
     CATEGORY_0_ITEMS.size()},
    {{"special_menu", "Special Holidays", "מועדים מיוחדים"}, CATEGORY_1_ITEMS.data(), CATEGORY_1_ITEMS.size()},
    {{"daily_menu", "Daily Prayers", "תפילות יומיות"}, CATEGORY_2_ITEMS.data(), CATEGORY_2_ITEMS.size()},
    {{"blessings_menu", "Blessings", "ברכות"}, CATEGORY_3_ITEMS.data(), CATEGORY_3_ITEMS.size()},
}};

inline constexpr std::array<NusachChoice, 4> NUSACH_CHOICES{{
    {"0", "Edot HaMizrach", "עדות המזרח"},
    {"1", "Sfarad", "ספרד"},
    {"2", "Ashkenaz", "אשכנז"},
    {"3", "Ari (Chabad)", "אר\"י (חב\"ד)"},
}};

}  // namespace Data
