#!/usr/bin/env python3
"""Generate the heap-free Siddur static navigation fixture header."""

import argparse
import json
from pathlib import Path


def cpp_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def generate(fixture: dict) -> str:
    navigation = fixture["navigation"]
    nusach = fixture["nusach"]
    lines = [
        "// Generated by scripts/generate_siddur_static_navigation.py. Do not edit.",
        "#pragma once",
        "",
        'namespace Data {',
        "",
    ]
    category_names = []
    for category_index, category in enumerate(navigation):
        name = f"CATEGORY_{category_index}_ITEMS"
        category_names.append(name)
        lines.append(f"inline constexpr std::array<MenuEntry, {len(category['items'])}> {name}{{{{")
        for item in category["items"]:
            lines.append(
                f"    {{{cpp_string(item['id'])}, {cpp_string(item['en'])}, {cpp_string(item['he'])}}},"
            )
        lines.extend(["}};", ""])

    lines.append(f"inline constexpr std::array<Category, {len(navigation)}> CATEGORIES{{{{")
    for category, item_name in zip(navigation, category_names):
        entry = (
            "    {{"
            f"{cpp_string(category['id'])}, {cpp_string(category['en'])}, {cpp_string(category['he'])}"
            "}"
        )
        single_line = f"{entry}, {item_name}.data(), {item_name}.size()}},"
        if len(single_line) > 120:
            lines.extend([f"{entry},", f"     {item_name}.data(),", f"     {item_name}.size()}},"])
        else:
            lines.append(single_line)
    lines.extend(["}};", ""])

    lines.append(f"inline constexpr std::array<NusachChoice, {len(nusach)}> NUSACH_CHOICES{{{{")
    for choice in nusach:
        lines.append(
            f"    {{{cpp_string(choice['value'])}, {cpp_string(choice['en'])}, {cpp_string(choice['he'])}}},"
        )
    lines.extend(["}};", "", "}  // namespace Data", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("fixture", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = generate(json.loads(args.fixture.read_text(encoding="utf-8")))
    if args.check:
        return 0 if args.output.read_text(encoding="utf-8") == rendered else 1
    args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
